Move ServiceCall to api module.
scalecube/scalecube-services pull request #620
Opened 2019-07-01 14:10 UTC by snripa

Allow to pass some fixed address to ServiceCall and let it be used instead of request routing.
As a consequence - it's up to Microservices to provide default router implementation (round-robin - as it was before)

2019-07-01 14:16 UTC, ronenhamias commented on services/src/main/java/io/scalecube/services/MicroservicesInjection.java
> +  private static boolean isService(Class<?> type) {
why not to use inject class for this?

2019-07-01 14:16 UTC, ronenhamias commented on services/src/main/java/io/scalecube/services/MicroservicesInjection.java
> +  private static void setField(Field field, Object object, Object value) {
why not to use inject class for this?

2019-07-02 12:58 UTC, artem-v requested changes

2019-07-02 12:58 UTC, artem-v commented on services-api/src/main/java/io/scalecube/services/Reflect.java
>  import static io.scalecube.services.CommunicationMode.REQUEST_RESPONSE;
Please  don't  re-arrange functions. It's hard to review what was changed. Please revert back methods aligment as it was.

2019-07-03 09:55 UTC, artem-v approved these changes

2019-07-03 12:15 UTC, ronenhamias approved these changes

2019-07-03 13:21 UTC, merged